# Generated by Django 3.0.4 on 2020-04-20 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200420_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_objects',
            name='author',
        ),
    ]
