# Generated by Django 3.0.4 on 2020-04-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_todo_objects_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_objects',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='todo_objects',
            name='title',
        ),
        migrations.AlterField(
            model_name='todo_objects',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
