# Generated by Django 3.0.4 on 2020-04-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200421_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_objects',
            name='added_date',
            field=models.DateTimeField(),
        ),
    ]
