# Generated by Django 3.0.4 on 2020-04-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20200421_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_objects',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
